events {
    # Event-Konfiguration
    worker_connections 1024;
}

http {
    include mime.types;  # Standard MIME-Typen

    # Logging
    error_log /var/log/nginx/error.log debug;

    # Server Block für dbmanager_fronted
    server {
        listen 80;

        root /usr/share/nginx/html;

        location /browser/dbmanager_fronted/ {
            index index.html;
            try_files $uri $uri/ /browser/dbmanager_fronted/index.html;
        }

        location /browser/ {
            index index.html;
            try_files $uri $uri/ /browser/index.html;
        }

        # Fallback für SPA
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
