events { }

error_log /var/log/nginx/error.log debug;

http {
    include mime.types;

    server {
        listen 80;
        root /usr/share/nginx/html;

        # Konfiguration für dbmanager_fronted
        location /browser/dbmanager_fronted/ {
            try_files $uri $uri/ /browser/dbmanager_fronted/index.html;
        }

        # Konfiguration für frontend
        location /browser/frontend/ {
            try_files $uri $uri/ /browser/frontend/index.html;
        }

        # Konfiguration für game-frontend
        location /browser/game/ {
            try_files $uri $uri/ /browser/game/index.html;
        }

        # Konfiguration für mameie-frontend
        location /browser/mameie/ {
            try_files $uri $uri/ /browser/mameie/index.html;
        }

        # Standard Fehlerseite für Angular SPAs
        error_page 404 /404.html;
        location = /404.html {
            try_files /404.html =404;
        }

        # MIME-Typen manuell ergänzen (optional)
        types {
            text/css css;
            application/javascript js;
            font/woff2 woff2;
        }

        # Cache-Konfiguration für statische Dateien
        location ~* \.(?:js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|mp4|webm|ogv|ogg|mp3|m4a|aac|flac|wav|webp)$ {
            expires 30d;
            add_header Cache-Control "public, immutable";
        }
    }
}
