events { }

error_log /var/log/nginx/error.log debug;

http {
    server {
        listen 80;

        # Konfiguration für dbmanager_frontend
        location /dbmanager_fronted/ {
             root /usr/share/nginx/html;
             try_files $uri $uri/ /dbmanager_fronted/browser/index.html;
             # MIME-Typen explizit festlegen
             types {
                  text/css css;
                  application/javascript js;
                  font/woff2 woff2;
             }
        }

        # Konfiguration für frontend
        location /frontend/ {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /frontend/browser/index.html;
        }

        # Konfiguration für game-frontend
        location /game/ {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /game/browser/index.html;
        }

        # Konfiguration für mameie-frontend
        location /mameie/ {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /mameie/browser/index.html;
        }

        # Fehlerseite
        error_page 404 /404.html;

        # Standard Fehlerseite für SPA
        location = /404.html {
            root /usr/share/nginx/html;
        }
    }
}
