version: '3'

services:
  serviceregistry:
    build:
      context: ./serviceregistry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
  apigateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "9050:9050"
