version: '3'

services:
  serviceregistry:
    build:
      context: ./serviceregistry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - eureka

  apigateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - eureka
    environment:
      - EUREKA_URI=http://serviceregistry:8761/eureka

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "9050:9050"
    networks:
      - eureka
    environment:
      - EUREKA_URI=http://serviceregistry:8761/eureka

networks:
  eureka:
    driver: bridge
