spring:
  application:
    name: datastorage
server:
  port: 9005
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

webDav:
  user: admin
  password: admin
  url: http://212.227.165.166/webdav/

