spring:
  application:
    name: system
server:
  port: 9001
  servlet:
    context-path: /system
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

securityUser:
  username: root
  password: dGVzdDEyMw==
  userCollection: SYSTEM_ADMIN
