spring:
  application:
    name: securitygateway
server:
  port: 9004
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
