spring:
  application:
    name: securitygateway
server:
  port: 9004
  servlet:
    context-path: /security
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

