spring:
  application:
    name: configmanager
server:
  port: 9002
  servlet:
    context-path: /configmanager
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
