spring:
  application:
    name: user
server:
  port: 9050
  servlet:
    context-path: /user
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
